### ISSUE TITLE
undefined columns selected

### ISSUE THREAD

**Issue by heaton2016** [AndreaCirilloAC/vizscorer#3]
Hi
I'm trying to test the scorer_bot, but get an error.
```
Error in `[.data.frame`(plot_object$data, , col_index) : 
  undefined columns selected
```
the plot_object is generate by the code below (you could igore some Chinese chracters).
```
pic1 = function(x){
  if(0 <= x & x< 10000){
    y = 8.75*(x/500)+25
  } else {
    y = 200
  }
}
x1 <- seq(0,10000,100)
df1 <- data.frame('距离'=x1,'比例尺'=map_dbl(x1,pic1),type = '0<=x<10000')
x2 <- seq(10000,20000,100)
df2 <- data.frame('距离'=x2,'比例尺'=map_dbl(x2,pic1),type = '10000<=x<20000')
df3 = rbind(df1,df2)
d <- df3
#画图
g = ggplot(d,aes(x = 距离, y= 比例尺))+
  geom_line(aes(colour=d$type))+xlab('与下一个机动点的距离（米）')+
  ylab('比例尺\n（米）')+theme(axis.title.y=element_text(angle=0))+
  labs(title='导航下比例尺变化图')+theme(plot.title=element_text(hjust=0.5))+
  expand_limits(x=0,y=0)+
  scale_x_continuous(expand = c(0,0),limits = c(0,21000))+
  scale_y_continuous(expand = c(0,0),limits = c(0,225))+
  scale_colour_hue('')
```
`scorer_bot(g)`

I can't figure out why this happen, need your help!

**Comment by AndreaCirilloAC** [comment]
hi @heaton2016, thank you for submitting this!
going to look into it within tomorrow.
tks

**Comment by AndreaCirilloAC** [comment]
Hi @heaton2016 
the issue you was experiencing derived from an inner logic of the ***mappings_lister()*** function, one of those employed from scorer_bot to analyse your plot.
This should be fixed with commit ffeb5771c4b5d5bff5280e11a8fa2a899cd8986e
I run the example you provided and everything went smoothly. Please try it by yourself and let me know how it works, so that we can close the issue.

thanks

**Comment by heaton2016** [comment]
Hi @AndreaCirilloAC 
I've tried it, and this time `scorer_bot(g) ` runs quite well. I think this commit fixes the problem.
However, the html file shows only the title "Your Plot Meta Analysis" and nothing else. I guess that here comes some "UTF-8" encoding problems, perhaps due to Chinese Characters in the file path?  I upload the zip file including the .Rmd and .html files, may this help.
I open the .Rmd file and find the suggestion is quite useful! Wish I could see the score_plot.
Thanks.


[plot_report.zip](https://github.com/AndreaCirilloAC/vizscorer/files/2752261/plot_report.zip)

**Comment by AndreaCirilloAC** [comment]
ok, so I am going to close this issue. I am also going to look into the .zip to understand what is going on with the report.
thanks.
